### ISSUE TITLE
Exception from HRESULT: 0x80042008

### ISSUE THREAD

**Issue by wshfdw** [WetHat/OnenoteTaggingKit#76] opened 2022-12-11 06:24 UTC
I'm definitely out of my element and may have just done something wrong/grabbed a wrong version or something (?), but after adding ~10-20 tags maybe with no issue and loving this as a solution, I've now started to get a "Severe Add-in Error" saying that "Page tagging failed! >>Exception from HRESULT: 0x80042008<<" probably 95+% of the time I try to add any tags, after the program stops responding for a bit. There _are_ some times it stops responding and then _does_ add tags though, and it probably happens a bit less for _removing_ tags, but is over all similar. (This includes after restarting the add-in, restarting the app. and/or restarting the computer, as well as when only opening OneNote.)

My OneNote on this computer I just downloaded straight from the site and it says it's 'Microsoft® OneNote® for Microsoft 365 MSO (Version 2211 Build 16.0.15831.20098) 32-bit,' if that matters!

Attaching a recent log, hopefully there's something I can do to be able to use this, it seems like a great tagging solution! (And hopefully this is the right place to ask for help, haha.) Thanks

[taggingkit_8DADA57BCC2C5B6.log](https://github.com/WetHat/OnenoteTaggingKit/files/10201577/taggingkit_8DADA57BCC2C5B6.log)

**Comment by WetHat** [comment] 2022-12-30 17:42
@wshfdw , thanks for providing a logfile. It is indeed very helpful. There seem to be several issues
* Remote procedure call failures. Error 0x8001010A. That is actually quite concerning because that is a low level
  problem which may indicate a computer configuration issue,
* Ink relelated errors: 0x80042008
* Concurrent page modifications. Error 0x80042010

I made several attempts to reproduce any of these errors, but was not able to. Maybe I'm missing something.
* Do you use any other add-ins besides the TaggingKit?
* Did you actually use any ink when errors occured?
* Were there any other OneNote dialogs open?
*  Were you editing an embedded Office document while tagging?
*  Did you use OneNote on docked mode

**Comment by WetHat** [comment] 2023-01-24 19:10
@wshfdw without any additional information, I must close this issue as _not reproducible_.

**Closed by WetHat** 2023-01-24 19:10 UTC
Labels: bug, not reprodicible
